services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 5432:5432
    environment:
        POSTGRES_PASSWORD: password
        POSTGRES_USER: user
        POSTGRES_DB: db
    volumes:
        - ./data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: guilherme@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
        - ./pgadmin:/var/lib/pgadmin
volumes:
    pgadmin:
    db: